<a href="https://colab.research.google.com/github/nick09k/AWP-Python-/blob/master/mini_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression


In [60]:
df = pd.read_csv('/content/drive/My Drive/smartknower/Admission_Predict.csv')

In [61]:

df.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [62]:
df.drop(['University Rating'], axis = 1) 

Serial No.  GRE Score  TOEFL Score  ...  CGPA  Research  Chance of Admit 
0             1        337          118  ...  9.65         1              0.92
1             2        324          107  ...  8.87         1              0.76
2             3        316          104  ...  8.00         1              0.72
3             4        322          110  ...  8.67         1              0.80
4             5        314          103  ...  8.21         0              0.65
..          ...        ...          ...  ...   ...       ...               ...
395         396        324          110  ...  9.04         1              0.82
396         397        325          107  ...  9.11         1              0.84
397         398        330          116  ...  9.45         1              0.91
398         399        312          103  ...  8.78         0              0.67
399         400        333          117  ...  9.66         1              0.95

[400 rows x 8 columns]

In [63]:
x =df.iloc[:,0:8].values
y = df.iloc[:,8].values

In [64]:
x

array([[  1.  , 337.  , 118.  , ...,   4.5 ,   9.65,   1.  ],
       [  2.  , 324.  , 107.  , ...,   4.5 ,   8.87,   1.  ],
       [  3.  , 316.  , 104.  , ...,   3.5 ,   8.  ,   1.  ],
       ...,
       [398.  , 330.  , 116.  , ...,   4.5 ,   9.45,   1.  ],
       [399.  , 312.  , 103.  , ...,   4.  ,   8.78,   0.  ],
       [400.  , 333.  , 117.  , ...,   4.  ,   9.66,   1.  ]])

In [65]:
train_X = x[0:320]
train_Y = y[0:320]

test_X = x[321:399]
test_Y = y[321:399]


In [66]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(train_X,train_Y)
y_pred = model.predict(test_X)
y_pred

array([0.7671319 , 0.71156226, 0.62847333, 0.68192919, 0.88251731,
       0.59446697, 0.56038562, 0.82953687, 0.53737955, 0.80484504,
       0.65443455, 0.68499277, 0.77393713, 0.78822906, 0.88744447,
       0.75696465, 0.98463511, 0.83919007, 0.83192248, 0.73646555,
       0.81710776, 0.68280552, 0.65703352, 0.50130295, 0.54919597,
       0.55249791, 0.4655987 , 0.50522874, 0.66052865, 0.74735114,
       0.83522076, 0.65827749, 0.63331344, 0.56921879, 0.69667501,
       0.83333582, 0.65220146, 0.60256486, 0.68705162, 0.83987502,
       0.9442013 , 0.97210294, 0.67212698, 0.79242163, 0.88098501,
       0.77637878, 0.56066642, 0.53503307, 0.62443319, 0.65828215,
       0.8493362 , 0.98089584, 0.77818789, 0.62375638, 0.58709027,
       0.51910032, 0.51950353, 0.56106398, 0.68771096, 0.8171684 ,
       0.78684413, 0.88232971, 0.66913273, 1.00742246, 1.03137547,
       0.63803008, 0.67726552, 0.55993183, 0.7920088 , 0.66941642,
       0.75643932, 0.88141145, 0.74231863, 0.90690241, 0.85147

In [67]:
test_Y 

array([0.73, 0.72, 0.62, 0.67, 0.81, 0.63, 0.69, 0.8 , 0.43, 0.8 , 0.73,
       0.75, 0.71, 0.73, 0.83, 0.72, 0.94, 0.81, 0.81, 0.75, 0.79, 0.58,
       0.59, 0.47, 0.49, 0.47, 0.42, 0.57, 0.62, 0.74, 0.73, 0.64, 0.63,
       0.59, 0.73, 0.79, 0.68, 0.7 , 0.81, 0.85, 0.93, 0.91, 0.69, 0.77,
       0.86, 0.74, 0.57, 0.51, 0.67, 0.72, 0.89, 0.95, 0.79, 0.39, 0.38,
       0.34, 0.47, 0.56, 0.71, 0.78, 0.73, 0.82, 0.62, 0.96, 0.96, 0.46,
       0.53, 0.49, 0.76, 0.64, 0.71, 0.84, 0.77, 0.89, 0.82, 0.84, 0.91,
       0.67])

In [71]:
from sklearn import metrics
metrics.mean_squared_error(test_Y,y_pred)

0.004918576101308849

In [72]:
metrics.r2_score(test_Y,y_pred)

0.7755907307447031

In [51]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 50)

In [52]:
x_train

array([0.59, 0.94, 0.79, 0.64, 0.54, 0.73, 0.72, 0.84, 0.78, 0.74, 0.82,
       0.72, 0.76, 0.77, 0.54, 0.93, 0.72, 0.64, 0.66, 0.62, 0.56, 0.71,
       0.7 , 0.61, 0.38, 0.82, 0.48, 0.65, 0.57, 0.62, 0.7 , 0.94, 0.96,
       0.64, 0.49, 0.96, 0.93, 0.93, 0.92, 0.52, 0.8 , 0.94, 0.67, 0.52,
       0.63, 0.76, 0.73, 0.91, 0.76, 0.92, 0.9 , 0.89, 0.94, 0.58, 0.67,
       0.71, 0.72, 0.39, 0.95, 0.74, 0.73, 0.78, 0.94, 0.58, 0.84, 0.7 ,
       0.71, 0.65, 0.8 , 0.92, 0.72, 0.78, 0.8 , 0.61, 0.68, 0.97, 0.52,
       0.85, 0.95, 0.77, 0.93, 0.71, 0.69, 0.58, 0.75, 0.64, 0.34, 0.71,
       0.69, 0.71, 0.86, 0.64, 0.48, 0.64, 0.79, 0.46, 0.79, 0.86, 0.91,
       0.53, 0.91, 0.73, 0.7 , 0.87, 0.58, 0.85, 0.57, 0.68, 0.84, 0.9 ,
       0.42, 0.89, 0.88, 0.54, 0.78, 0.71, 0.79, 0.73, 0.63, 0.7 , 0.57,
       0.72, 0.49, 0.7 , 0.59, 0.94, 0.76, 0.65, 0.52, 0.93, 0.46, 0.61,
       0.59, 0.63, 0.65, 0.95, 0.72, 0.8 , 0.83, 0.62, 0.89, 0.74, 0.78,
       0.81, 0.74, 0.49, 0.92, 0.68, 0.47, 0.62, 0.

In [70]:
from sklearn import metrics

# Mean Squared Error 
metrics.mean_squared_error(y_test,y_pred)
# Accuracy Score

metrics.r2_score(y_test,y_pred)

ValueError: ignored